#!/usr/bin/sh

c_bright=$(qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/BrightnessControl org.kde.Solid.PowerManagement.Actions.BrightnessControl.brightness)

if [ ! $# -eq 0 ] && [ $1 = "-" ]
then
    c_bright=$(expr "$c_bright" - 50)
elif  [ ! $# -eq 0 ] && [ $1 = "+" ]
then
    c_bright=$(expr "$c_bright" + 50)
fi

qdbus org.kde.Solid.PowerManagement /org/kde/Solid/PowerManagement/Actions/BrightnessControl org.kde.Solid.PowerManagement.Actions.BrightnessControl.setBrightness "$c_bright"
