#!/usr/bin/sh

# copy songs in $new_songs to $out
# adds them to $old_songs playlist
# resets the $new_songs
new_songs="$HOME/.mpd/playlists/new_loved_songs.m3u"
old_songs="$HOME/.mpd/playlists/old_loved_songs.m3u"
out="$HOME/Desktop/.temp.mp3"

n_songs=$(wc -l "$HOME/.mpd/playlists/new_loved_songs.m3u" | cut -d ' ' -f1)

while read -r song; do
     if [ -f "$song" ]; then
          song_to_phone "$song"
          # update loved songs playlist
          echo "$song" >>"$old_songs"
     else
          echo "$song" invalid 1>&2
     fi
done <"$new_songs"
truncate -s 0 "$new_songs"

kdialog --title "Music Library:" --passivepopup \
     "$n_songs new songs exported" \
     --icon "speakers"
