#!/usr/bin/sh

mkdir -p wallpapers
cd wallpapers || exit
i=1
while [ "$i" -ne 5 ]; do
	wget https://clients3.google.com/cast/chromecast/home -O - | grep -oP '(?<=content\.com\\\/proxy\\\/)[^\\]+(?=\\\\u003)' | xargs -P 4 -I {} bash -c "wget https://lh\$(shuf -i 3-6 -n 1).googleusercontent.com/proxy/{}=s0 -O \$(echo -n {} | md5sum | cut -c 1-32).jpg -nc -nv"
	i=$((i + 1))
done
