#!/usr/bin/sh

status="$(mpc status | rg -oP "(?<=\[).*(?=\])" )"

if [ "$status" = "playing" ]
then
    mpc pause
    status="song paused"
elif [ "$status" = "paused" ]
then
    mpc play
    status="song playing"
fi

mpddunst "$status"

exit
