#!/usr/bin/sh

INFO="$(mpc status | head -1)"

dunstify    -a "Music player:" \
            "$(echo "$INFO" | cut -d - -f 1)" \
            "$(echo "$INFO" | cut -d - -f 2)" \
            -i "$(mpd_albumcover)"

#same thing but with awk instead of cut
#dunstify "$(mpc status | head -1 | awk -F ' - ' '{print $1"\n"$2}')" -i "$(mpd_albumcover)"
