#!/usr/bin/sh

# show the percentage of songs loved per artist album

# since some artist had , in the name i had to change the separator to ;
# grab all loved songs and count them by artist and album, output [number];[artist] and [number];[artist album]
cut ~/.mpd/playlists/old_loved_songs.m3u -d / -f 5,6 | sort |  uniq -c | sed 's|^[ \t]*||;s| |\;"|;s|$|"|' > /tmp/count.txt.r
cut ~/.mpd/playlists/old_loved_songs.m3u -d / -f 5 | sort |  uniq -c | sed 's|^[ \t]*||;s| |\;"|;s|$|"|' >> /tmp/count.txt.r

# grab all loved songs and count them by artist and album, output [number];[artist] and [number];[artist album]
fd . "$MUSIC" -e mp3 | cut -d / -f 5,6 | sort | uniq -c | sed 's|^[ \t]*||;s| |\;"|;s|$|"|' > /tmp/tot_count.txt.r
fd . "$MUSIC" -e mp3 | cut -d / -f 5 | sort | uniq -c | sed 's|^[ \t]*||;s| |\;"|;s|$|"|' >> /tmp/tot_count.txt.r

# csv headers
echo "Band;Total;Loved;Percent" > /tmp/report.txt.r

# join the two files, with [artist] as common, create a column with the percentage of loved songs
xsv join -d ";" -n --full 2 /tmp/tot_count.txt.r 2 /tmp/count.txt.r | xsv select 2,1,3 | xsv fmt -t ";" | rg -vi "^;" | awk -F ";" '{if (NF == 3) {print $0";" $3/$2*100"%"} else {print $0";" 0"%"}}' | xsv select -d ";" 1,3,2,4 | xsv fmt -t ";" | sed 's|;;|;0;|' >> /tmp/report.txt.r

# make the report easy on the eyes
xsv sort -d ";" -s "Band" /tmp/report.txt.r > ~/Desktop/final_report.txt

# notify
kdialog --title "Music Library:"  --passivepopup \
            "Music Report exported" \
            "to ~/Desktop/final_report.txt" \
            --icon  "bell"

rm /tmp/*.txt.r

## old and retarded
#
# fd . '/mnt/sdb3/Music/' -e mp3 | cut -d / -f 5 | uniq -c > ~/Desktop/tot_count.txt
# cut ~/.mpd/playlists/old_loved_songs.m3u -d / -f 5 | uniq -c > ~/Desktop/count.txt
#while read -r line_total
#do
#    id_total=$(echo "$line_total" | cut -d ' ' -f 2-)

#    line_playlist= rg "$id_total" "$2"
#    num_play=$(echo "$line_playlist" | cut -d ' ' -f 1)
#    num_total=$(echo "$line_total" | cut -d ' ' -f 1)
#    perc=$((num_play * 100 / num_total))
#    echo "$perc"% "$id_play" Loved songs: "$num_play"
#    (>&2 echo "$id_play" checked)

    # while read -r line_playlist
    # do
    #     id_play=$(echo "$line_playlist" | cut -d ' ' -f 2-)
    #     if [ "$id_play" = "$id_total" ]
    #     then
    #         num_play=$(echo "$line_playlist" | cut -d ' ' -f 1)
    #         num_total=$(echo "$line_total" | cut -d ' ' -f 1)
    #         perc=$((num_play * 100 / num_total))
    #         echo "$perc"% "$id_play" Loved songs: "$num_play"
    #         (>&2 echo "$id_play" checked)
    #         break
    #     fi
    # done < "$2"
#done < "$1"
#(>&2 echo Done!)
