#!/usr/bin/sh

URL=https://www.reddit.com/r/EarthPorn/top/.json
QUERY="?after="
ARGS2=""

if [ "$1" ]; then
    T="$1"
else
    T=10
fi

if [ "$2" ]; then
    ARGS="$2"
else
    ARGS=""
fi

i=1

while [ "$i" -ne "$T" ]; do
    curl -s "$URL$QUERY$ARGS" |
        jq ".data.children[].data.url" | tr -d "\"" |
        rg ".*.(jpe|jp|pn)g$" | parallel curl {} -s -O

    ARGS2="$(curl -s "$URL$QUERY$ARGS" |
        jq ".data.after" | tr -d "\"")"

    if [ "$ARGS2" = "null" ]; then
        echo "API request full"
        echo "Keep up from here"
        echo "reddit_img_download 10 ""$ARGS"
        exit
    else
        ARGS="$ARGS2"
    fi

    i=$((i + 1))
    echo "Going for:"
    echo "$URL$QUERY$ARGS"

done

echo "Keep up from here"
echo "$ARGS"
