#!/usr/bin/bash

new_songs="$HOME/.mpd/playlists/new_loved_songs.m3u"
old_songs="$HOME/.mpd/playlists/old_loved_songs.m3u"
back_up="$HOME/.mpd/playlists/backup/"

mkdir -p "$back_up"
cp "$new_songs" "$back_up"new_loved_songs$(date "+%y%m%d%H%M%S").m3u.bak
cp "$old_songs" "$back_up"old_loved_songs$(date "+%y%m%d%H%M%S").m3u.bak

# update new_loved_songs
comm -23 <(sort -u "$new_songs") <(sort -u "$old_songs") >/tmp/temp
mv /tmp/temp "$new_songs"

# update old_loved_songs
sort -u "$old_songs" >/tmp/temp
mv /tmp/temp "$old_songs"

cp "$old_songs" "$DOCS"

# leave only the 4 last playlist backups
#ls -1 -t | tail -$(echo "$(ls -1 | wc -l) - 4" | bc) | parallel rm
